sudo: required

language: node_js
node_js:
- node

services:
- docker

script:
- npm test
notifications:
  email:
    on_success: never
addons:
  ssh_known_hosts: "$DEPLOY_SERVER_IP"
before_deploy:
- openssl aes-256-cbc -K $encrypted_c9a7a818a29a_key -iv $encrypted_c9a7a818a29a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker build -t arnaudforaison/proxilabs-bot .
- docker login -u="$DOCKER_ID_USER" -p="$DOCKER_PWD_USER"
deploy:
  provider: script
  skip_cleanup: true
  script: docker push $DOCKER_ID_USER/proxilabs-bot
  on:
    branch: develop
after_deploy:
- rsync -r --delete-after --quiet -e "ssh -o StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR/dist/* root@$DEPLOY_SERVER_IP:~/proxilabs-bot
- ssh -o StrictHostKeyChecking=no root@$DEPLOY_SERVER_IP '~/proxilabs-bot/deploy.sh'