dist: precise
language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_c9a7a818a29a_key -iv $encrypted_c9a7a818a29a_iv
  -in deploy_key.enc -out ./deploy_key -d
script:
- npm run build
notifications:
  email:
    on_success: never
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && scp dist/* root@$DEPLOY_SERVER_IP:~/proxilabs-bot
  on:
    branch: develop
